Repository CRU-RAG/cru-rag-system, pull requests merged in 2024-10, with the labels that each got.

#9 TASK | #1 | Setup docker containers for cru rag
  .env.example
  .gitignore
  Dockerfile
  Readme.md
  docker-compose.yml
  main.py
  requirements.txt
Labels: TASK

#12 DOCS | #11 | Add more info to readme
  README.md
  Readme.md
Labels: DOCS

#10 FEATURE | #2 | Create a rag server based on websocket
  main.py
Labels: FEATURE

#13 FEATURE | #6 | Implement weaviate services
  schema.json
  services/weaviate/weaviate_service.py
  utilities/__init__.py
  utilities/file_utilities.py
Labels: FEATURE

#14 FEATURE | #7 | Embedder based on weaviate service
  docker-compose.yml
  embedder.py
Labels: FEATURE

#18 CLEANUP | #6 | Code cleanup
  Dockerfile
Labels: CLEANUP

#19 CLEANUP | #6 | Cleanup
  .env.example
Labels: CLEANUP

#20 TEST | #17 | Basic test script for the weaviate service
  test_embedder.py
Labels: TEST

#22 FEATURE | #21 | implemented delete operation on the weaviate service
  services/weaviate/weaviate_service.py
  test_embedder.py
Labels: FEATURE

#23 CLEANUP | #21 | test_embedder: code cleanup
  test_embedder.py
Labels: CLEANUP

#24 FEATURE | #15 | Configure rabbitmq
  embedder.py
  test_weaviate_service.py
Labels: FEATURE

#25 FEATURE | #5 | Manage query with the llm
  main.py
  message/message_manager.py
  services/openai/langchain_service.py
  services/redis/redis_service.py
  utilities/string_utilities.py
  utilities/weaviate_utilities.py
Labels: FEATURE

#27 TASK | #26 | Define VerseWise persona
  message/message_manager.py
Labels: TASK

#29 TASK | #28 | Populate versewise persona
  message/message_manager.py
Labels: TASK

#31 FEATURE | #30 | Telegram bot interface
  .env.example
  bot.py
  docker-compose.yml
  requirements.txt
Labels: FEATURE

#32 CLEANUP | #30 | Code cleanup
  .env.example
Labels: CLEANUP

#34 TASK | #33 | Optimized WiseVerse persona
  message/message_manager.py
Labels: TASK
